Create model and repository organization
alkemyTech/OT184-server pull request #18
Opened 2022-04-18 13:20 UTC by pueblandres

Organization entity is created.
organization repository is created.

2022-04-18 14:29 UTC, paoliellolucas requested changes

2022-04-18 14:29 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/OrganizationEntity.java
> +package com.alkemy.ong.data.entity;
pongamosla en el paquete entities

2022-04-18 14:29 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/repository/OrganizationRepository.java
> +package com.alkemy.ong.data.repository;
ubiquémosla en repositories

2022-04-18 14:29 UTC, paoliellolucas commented on src/main/resources/application.yaml
> +    password: root
q las password no vayan seteadas aca. debería estar vacío o como var de entorno.

2022-04-18 16:36 UTC, pueblandres commented
cambio de nombre a los paqutes.
elimine la contraseña de la configuracion.

2022-04-19 15:19 UTC, paoliellolucas approved these changes

2022-04-19 15:22 UTC, merged