modelo y repositorio de News
alkemyTech/OT184-server pull request #2
Opened 2022-04-15 00:49 UTC by Lucases27

Ticket: OT184-19

Creacion de _NewsEntity_, _NewsRepository_.

En _schema.sql_, agregué el script de la tabla news para probar que funcionara. Y lo dejé aunque quizás no debería, porque el ticket no lo pide.

2022-04-15 12:33 UTC, paoliellolucas requested changes

2022-04-15 12:33 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/dto/NewsDTO.java
> +package com.alkemy.ong.data.dto;
esta clase no va para este ticket. Si queres stasheala para usarla en el proximo ticket.
Igualmente al dto lo vamos a hacer dentro del controller.

2022-04-15 12:33 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +   created_at timestamp NULL,
este es not null tmb

2022-04-15 12:33 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +   is_deleted BIT(1) NULL,
este tmb not null

2022-04-15 12:33 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/NewsEntity.java
> +    @ManyToOne(fetch = FetchType.EAGER,
todo esto coméntalo porque todavía no esta category y va a pinchar

2022-04-15 12:33 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/NewsEntity.java
> +    @PrePersist
en lugar de usar estos prePersist y preUpdate podes usar las anotaciones:
@CreationTimestamp y @UpdateTimestamp que hacen lo mismo!

2022-04-15 18:13 UTC, Lucases27 commented on src/main/resources/schema.sql
> +   created_at timestamp NULL,
is_deleted o created_at ? o ambos?

2022-04-16 13:36 UTC, paoliellolucas requested changes

2022-04-16 13:36 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/repository/NewsRepository.java
> +public interface NewsRepository extends JpaRepository<NewsRepository, Long> {
JpaRepository debe recibir la entidad. Sino al levantar la app falla.

2022-04-16 13:36 UTC, paoliellolucas commented on src/main/resources/schema.sql
> +CREATE TABLE news (
podemos agregar q la cree si no existe?
CREATE TABLE IF NOT EXISTS table_name(

2022-04-18 12:27 UTC, paoliellolucas approved these changes

2022-04-18 12:27 UTC, merged