OT184-81 Agregar paginación a novedades
alkemyTech/OT184-server pull request #31
Opened 2022-04-21 19:49 UTC by Lucases27

**Ticket: OT184-81**

NewsController method _findByPage_ implemented.
Util class **PageResponse**: Contains a List of _type <T>_, and two strings with the urls, _nextPage_ and _previousPage_. Where the url to the following List will be indicated, if it exists.

**Method:** GET 
**Path:** news
**Param:** ?page

**Database:**
![image](https://user-images.githubusercontent.com/75321699/164540697-e7f1ad04-79e1-4a7c-b28b-50374ddf5d9e.png)

**Successful case 1 :** first page. 200 OK, 
![image](https://user-images.githubusercontent.com/75321699/164540968-9bb756b5-4a01-41a7-9319-cd516f6299dd.png)

**Successful case 1 :** last page. 200 OK, 
![image](https://user-images.githubusercontent.com/75321699/164540793-a28af42f-6dde-4be2-9324-9394c5161f57.png)

**Successful case 1 :** middle page. 200 OK, 
![image](https://user-images.githubusercontent.com/75321699/164541027-b3e999b9-c9d1-4784-bb81-3f37823f1dbd.png)

**Error Case 1:** 
![image](https://user-images.githubusercontent.com/75321699/164541165-986fee8d-3d86-443b-91c9-d916bd07c5cd.png)

**Error Case 2:** 
![image](https://user-images.githubusercontent.com/75321699/164541228-2870f5f5-61e6-406a-8e84-78588396ca3d.png)

**Error Case 3:**
![image](https://user-images.githubusercontent.com/75321699/164541280-c53be281-fa7d-490c-a4bb-b1cd3c9d6661.png)

2022-04-21 20:39 UTC, paoliellolucas requested changes

2022-04-21 20:39 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultNewsGateway.java
> +        return this.toModel(optional.get());
simplifiquemos este metodo. Te debería poder quedar algo asi:
NewsEntity news = repo.findById(id).orElseThrow(()->,=..);
return toModel(news);

2022-04-21 20:39 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/news/NewsService.java
> +        final int SIZE = 10;
este size deberíamos definirlo como variable externa en el application.yaml

2022-04-21 20:39 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/news/NewsService.java
> +    NewsRepository newsRepository;
no hay q pegarle al repository. Tenemos q ir atravesando el gateway como siempre

2022-04-21 20:39 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/NewsController.java
> +        int size = 10;
esto lo deberíamos leer como variable externa definida en el application.yaml

2022-04-21 20:39 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/NewsController.java
> +        List<NewsDTO> newsDTOList = newsService.findByPage(pageNumber-1)
no hagamos el pageNumber -1. Si en el controller me llega el 0, sabemos q es la pagina 0 (q seria la primera)

2022-04-21 20:39 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/utils/PageResponse.java
> +    public PageResponse(List<T> content, String path, int pageNumber, int size) {
el content no va a tener siempre 10 registros? como sabes si hay mas paginas o no?

2022-04-22 02:25 UTC, Lucases27 commented on src/main/java/com/alkemy/ong/web/controllers/utils/PageResponse.java
> +    public PageResponse(List<T> content, String path, int pageNumber, int size) {
Para poder saber eso, ahora implementé una clase model, que además de tener la lista, tiene el total de paginas.

2022-04-22 12:58 UTC, paoliellolucas requested changes

2022-04-22 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/utils/PageResponse.java
> +            throw new ResourceNotFoundException("resource");
en realidad, cuando es una falla por ?page=X no deberíamos devolver un 404 (q es para los recursos q no existen). En realidad aca es un error del cliente y lo mas apropiado seria un 400 Bad Request

2022-04-22 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/utils/PageResponse.java
> +    public PageResponse(List<T> dtoList, String path, int pageNumber, int pageSize, int totalPages) {
en lugar de dtoList, llamalo content. Queda mas lindo

2022-04-22 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/exceptions/RestExceptionHandler.java
> +                HttpStatus.NOT_FOUND,
aca mapealo a BAD_REQUEST en lugar de NOT_FOUND

2022-04-22 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/NewsController.java
> +        PageResponse<NewsDTO> pageResponse = new PageResponse<>(pageNewsDTO.getContent()
como el PageResponse recibe una lista genérica, no es necesario que tmb hagas una PageNewsDto. Podrías pasarle directamente la PageNews no?

2022-04-22 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/news/PageNews.java
> +package com.alkemy.ong.domain.news;
En lugar de tener una PageNews, podemos tener una PageModel o PageData para que todos usemos la misma.
podría estar en domain.utils.PaginationUtils

2022-04-22 12:58 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/gateways/DefaultNewsGateway.java
> +    private PageNews pageToModel(Page<NewsEntity> page){
en lugar q este aca, tendriamos q hacer la conversion de page a model en otro lugar asi todos usan lo mismo ya que va a ser todo repetido sino.
En data.utils.PaginationUtils podrías hacer una conversion genérica

2022-04-22 13:06 UTC, Lucases27 commented on src/main/java/com/alkemy/ong/web/controllers/utils/PageResponse.java
> +            throw new ResourceNotFoundException("resource");
Sí, estaba en duda entre esos 2, gracias!

2022-04-22 13:06 UTC, Lucases27 commented on src/main/java/com/alkemy/ong/web/controllers/utils/PageResponse.java
> +    public PageResponse(List<T> dtoList, String path, int pageNumber, int pageSize, int totalPages) {
Es cierto!!

2022-04-22 13:09 UTC, Lucases27 commented on src/main/java/com/alkemy/ong/web/controllers/NewsController.java
> +        PageResponse<NewsDTO> pageResponse = new PageResponse<>(pageNewsDTO.getContent()
Recibe una lista generica sí, pero la lista que viene desde domain dentro de PageNews es de tipo model. Si se la paso directamente tendria que hacer el mapeo a dto ahí dentro.

2022-04-22 14:34 UTC, Lucases27 commented on src/main/java/com/alkemy/ong/data/gateways/DefaultNewsGateway.java
> +    private PageNews pageToModel(Page<NewsEntity> page){
Lo estoy tratando de hacer, pero tengo un problema para convertir el content, es decir la lista de las entity a model, porque cada una llama a su metodo toModel() y estan declarados en defaultgateway distintos.

2022-04-22 18:11 UTC, paoliellolucas approved these changes

2022-04-22 18:11 UTC, merged