Ot184 68 endpoint to list members
alkemyTech/OT184-server pull request #6
Opened 2022-04-16 09:51 UTC by Francisco2020-Ra

2022-04-16 14:07 UTC, paoliellolucas requested changes

2022-04-16 14:07 UTC, paoliellolucas commented on pom.xml
> +		<dependency>
tratemos d solo usar Lombok. Tiene un builder q esta bueno

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/OngApplication.java
> +	@Bean
sin modelMapper

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/entity/MembersEntity.java
> +package com.alkemy.ong.data.members.entity;
cuando mergeemos el otro branch, y hagas el merge, esto no debería figurar como parte de este PR.

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/MembersIEntity.java
> +    List<MembersModel> getAll();
llamemos Members al modelo (en lugar de MembersModel).
Dsp el dto seria MemberDto y la entity es MemberEntity

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/impl/MembersIEntityImpl.java
> +    @Autowired
usemos la inyección de dependencia x constructor q es la mas recomendada

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/impl/MembersIEntityImpl.java
> +    private MembersRepository membersRepository;
las dependencias suelen ser final ya q no cambien. Sumemosle eso

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/model/MembersModel.java
> +public class MembersModel {
renombre clase a Members

2022-04-16 14:07 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/model/MembersModel.java
> +    public Long getId() {
Lombok tiene @Data q reemplaza a los getters y setters. Pegale una mirada

2022-04-18 13:17 UTC, paoliellolucas requested changes

2022-04-18 13:17 UTC, paoliellolucas commented on pom.xml
> +			<groupId>org.modelmapper</groupId>
borremos esta dependencia

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/OngApplication.java
> +	public ModelMapper modelMapper(){
borremos esto tmb ya q no lo vamos a usar

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/DefaultGateway.java
> +package com.alkemy.ong.data.members.service;
como data es infra, no nos interesa dividir por use case. Asi que podemos tener entities, repositories y gateways. Trata q queden asi.

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/DefaultGateway.java
> +@Service
Falta el service en domain. Se debería llamar MemberService e inyectar la interfaz gateway.
Esta clase de gateway debería usar la anotación @Component ya q no es un service

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/DefaultGateway.java
> +public class DefaultGateway implements Gateway {
renombre a DefaultMemberGateway y que implemente MemberGateway

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/DefaultGateway.java
> +    @Autowired
no es requerido el autowired, desde las ultimas versiones ya no es necesario

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/DefaultGateway.java
> +
con una linea en blanco es suficiente

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/members/service/DefaultGateway.java
> +        entity.forEach((MemberEntity) -> model.add(
en lugar del foreach podemos usar lambdas:
Te quedaria algo del tipo: 
return membersRepo.findAll().stream()
  .map(e -> toModel(e)) // este toModel es un metodo privado en el q harías la conversion
  .collect(toList());

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/members/controller/MembersController.java
> +
con una linea en blanco es suficiente

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/members/controller/MembersController.java
> +    @Autowired
no es necesario

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/members/controller/MembersController.java
> +    public MembersController (Gateway gateway){
el controller no debería inyectar el gateway. Debería inyectar un Service

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/members/controller/MembersController.java
> +        membersModels.forEach((Members) -> memberDTO.add(
usemos lambda. Aplica la misma lógica q te marque para el defaultGateway

2022-04-18 13:17 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/members/dto/MemberDTO.java
> +public class MemberDTO {
ya que este dto lo usa solamente tu clase controller, podemos definirla dentro del controller como una inner class.
Elimina esta clase y definila directamente en el controller

2022-04-19 14:21 UTC, paoliellolucas requested changes

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/entity/MemberEntity.java
> +package com.alkemy.ong.data.entity;
movámoslos al paquete entities

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/repository/MembersRepository.java
> +package com.alkemy.ong.data.repository;
movámoslo al paquete repositories

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/service/DefaultMemberGateway.java
> +package com.alkemy.ong.data.service;
movámoslos al paquete data.gateways

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/service/DefaultMemberGateway.java
> +@Service
ya q es un componente y no un servicio propiamente dicho, usemos la anotación @Component

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/service/DefaultMemberGateway.java
> +            .collect(Collectors.toList());
usemos static imports asi podemos leer .collect(toList()); el Collectors.toList() es redundante ya q estamos dentro del metodo collect

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/data/service/MemberGateway.java
> +package com.alkemy.ong.data.service;
Esta interfaz no tiene sentido. En data solo vamos a tener la MemberDefaultGateway que implementa la interfaz MemberGateway que tiene q estar en domain.members

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/model/Members.java
> +package com.alkemy.ong.domain.members.model;
moverlo al paquete domain.members

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/service/Gateway.java
> +package com.alkemy.ong.domain.members.service;
moverla a domain.members

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/service/Gateway.java
> +public interface Gateway {
renombre a MemberGateway. Esta es la q implementa el DefaultMemberGateway q esta en data

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/service/MemberService.java
> +public class MemberService implements Gateway {
esta no implementa a nadie.

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/members/service/MemberService.java
> +    private DefaultMemberGateway defaultMemberGateway;
en domain no podemos conocer nada de data. Tenemos q usar la interfaz aca en lugar de la implementación.
MemberGateway hay q usar

2022-04-19 14:21 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/members/controller/MembersController.java
> +                .collect(Collectors.toList()));
usar static import en Collectors.toList(). Con botón derecho t debería dar la opción de agregar static import asi elimina Collectors y solo queda toList()

2022-04-20 16:13 UTC, Francisco2020-Ra commented
Pull request duplicado

2022-04-20 16:13 UTC, closed without merging