Ot184-33 Validate find by ID
alkemyTech/OT184-server pull request #64
Opened 2022-05-04 04:41 UTC by nicolaspucci1989

* Validate user role when making GET a request to /user/id
* If user has "admin" role or the requested id matches the currently authenticated user id return the requested data.
* Else return the currently authenticated user data.

### Evidence
![image](https://user-images.githubusercontent.com/21686704/166623594-ef973c7b-d209-48c3-bfd8-0d151a6fa4db.png)
#### Non admin user sends a GET request to /users/{id}. Endpoint returns the currently authenticated user data.
![image](https://user-images.githubusercontent.com/21686704/166623621-51d7ddf6-4a16-47fb-b30e-22baa73897ad.png)
#### Admin user sends a GET request to /users/{id}. Endpoint returns the requested user data.
![image](https://user-images.githubusercontent.com/21686704/166623633-0c8aa825-d5b3-46e4-b051-f8874864cf40.png)

2022-05-04 12:42 UTC, paoliellolucas requested changes

2022-05-04 12:42 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/UserController.java
> +    if (Objects.equals(foundUser.getEmail(), principal) ||
en realidad lo primero q hay q hacer es validar si se puede proseguir con la operación con el id que se quiere buscar y la información del contexto de la seguridad. Podrías traerte el token con el q se esta loqueando y ese ya tiene la informacion del mail, ahí haces la comparación y dsp proseguis con el findById

2022-05-04 12:42 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/UserController.java
> +      return ResponseEntity.ok(toDto(foundUser));
off topic, pero me cambias en authController el singIn por sign in en el nombre del metodo?

2022-05-04 16:22 UTC, nicolaspucci1989 commented on src/main/java/com/alkemy/ong/web/controllers/UserController.java
> +      return ResponseEntity.ok(toDto(foundUser));
se renombra a login

2022-05-05 12:20 UTC, paoliellolucas approved these changes

2022-05-05 12:20 UTC, merged