Endpoint create slides
alkemyTech/OT184-server pull request #69
Opened 2022-05-06 12:05 UTC by pueblandres

Lucas lo subo para que lo veas, a ver que estoy haciendo mal, aun no funciona.

2022-05-10 12:36 UTC, paoliellolucas requested changes

2022-05-10 12:36 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/domain/slide/SlideService.java
> +      //  if(slide.getOrder()==null){
que pasa si la primera vez no hay registros en la tabla y no le paso el slide? no habría q comparar con null?

2022-05-10 12:36 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/SlideController.java
> +            slideBasicDTO.setOrder(slidesRepository.findOrder()+1);
esta logica mejor que este en el service

2022-05-10 12:36 UTC, paoliellolucas commented on src/main/java/com/alkemy/ong/web/controllers/SlideController.java
> +    public ResponseEntity<SlideBasicDTO> save( @RequestBody SlideBasicDTO slideBasicDTO, @PathVariable Long id) throws IOException {
queda raro q llegue el id de organization solo por path.. agrégalo en el slideBasicDto mejor

2022-05-10 12:36 UTC, paoliellolucas commented on src/main/resources/schema.sql
> -CREATE TABLE comments (
por que estas borrando esta?

2022-05-10 12:36 UTC, paoliellolucas commented on pom.xml
> +            <groupId>org.springframework</groupId>
es necesaria esta dependency?

2022-05-10 15:12 UTC, pueblandres commented on src/main/resources/schema.sql
> -CREATE TABLE comments (
no me di ni cuenta, agregado.

2022-05-10 22:34 UTC, pueblandres commented
listo los cambios

2022-05-11 01:40 UTC, paoliellolucas approved these changes

2022-05-11 01:40 UTC, merged